###################################################################
# Project Configuration: 
# 
# Specify the name of the design (project) and the Quartus II
# Settings File (.qsf)
###################################################################

PROJECT = vga
TOP_LEVEL_ENTITY = top_level

###################################################################
# Part, Family, Boardfile DE1 or DE2
FAMILY = Cyclone V
PART = 5CSXFC6D6F31C6
BOARDFILE = general/DE10_STD_GHRD
###################################################################

REMOTE_USER = $(USER)
REMOTE_HOST = $(HOSTNAME)

-include ../Makefile
